### ISSUE TITLE
Subserv crashes once when creating broker

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/subserv#1]
Got these in the log after starting up a clean enmasse-template.yaml instance:

connecting to configuration service...
starting to watch pods for topic mytopic
watching pods serving mytopic
subscribing with path: /api/v1/watch/namespaces/myproject/pods?labelSelector=address%3Dmytopic
STATUS: 200
pod added for mytopic: {"name":"topic-mytopic-1-okyj2","ip":"172.17.0.10","status":"Running","ready":true,"ports":{"broker":{"amqp":5673,"core":61616},"router":{"amqp":5672},"forwarder":{"health":8080}}}
[connection-3] disconnected
[connection-4] disconnected
[connection-5] disconnected
pod added for mytopic: {"name":"topic-mytopic-1-4m6q3","status":"Pending","ready":true,"ports":{"broker":{"amqp":5673,"core":61616},"router":{"amqp":5672},"forwarder":{"health":8080}}}
[topic-mytopic-1-4m6q3] error: Error: connect ECONNREFUSED
[topic-mytopic-1-4m6q3] disconnected
/node_modules/rhea/lib/transport.js:68
P protocol id ' + this.header_received.protocol_id + ' expecting: ' + this.pro
                                                                    ^
Error: Invalid AMQP protocol id 0 expecting: 3
    at Error (native)
    at Transport.read (/node_modules/rhea/lib/transport.js:68:109)
    at SaslServer.read (/node_modules/rhea/lib/sasl.js:185:31)
    at Connection.input (/node_modules/rhea/lib/connection.js:370:31)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by lulf** [comment]
Script to reproduce:

sudo oc cluster down
sudo oc cluster up
sleep 5
oc login -u developer -p developer
oc policy add-role-to-user view system:serviceaccount:$(oc project -q):default
oc policy add-role-to-user edit system:serviceaccount:$(oc project -q):deployer
oc process -f enmasse-template.yaml | oc create -f -

Using latest openshift-configuration (a80eac6b40764a5ab9735b574caae6c8348e3925)

**Comment by grs** [comment]
The error indicates that subserv was expecting a sasl header, but the peer responded with a plain amqp header. Not sure how that happens as yet.

**Comment by lulf** [comment]
I'm seeing the same issue with a slightly different error message if I try to run the following command against the subscription service:

qpid-send -a '$subctrl' -b 172.30.48.76:5672 --content-stdin

Then the subscription service crashes with:

/node_modules/rhea/lib/transport.js:68
P protocol id ' + this.header_received.protocol_id + ' expecting: ' + this.pro
                                                                    ^
Error: Invalid AMQP protocol id 1 expecting: 3
    at Error (native)
    at Transport.read (/node_modules/rhea/lib/transport.js:68:109)
    at SaslServer.read (/node_modules/rhea/lib/sasl.js:185:31)
    at Connection.input (/node_modules/rhea/lib/connection.js:370:31)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)

**Comment by lulf** [comment]
Status update after doing some more investigation:

This happens when connecting to the co-located router of the broker pod. I've saved a wireshark packet trace here: http://people.redhat.com/~ulilleen/subserv_connerror.pcapng 

Filter by port==5672 and look for address 127.0.0.1 .

**Comment by grs** [comment]
> This happens when connecting to the co-located router of the broker pod. I've saved a wireshark
 > packet trace here: http://people.redhat.com/~ulilleen/subserv_connerror.pcapng
>
> Filter by port==5672 and look for address 127.0.0.1 .

The subserv is not colocated with the router though, so how would it be using 127.0.0.1 to connect?

**Comment by lulf** [comment]
I ran subserv outside openshift setting the appropriate environment variables for it to connect to the hosts in openshift (made it easier to make modifications and test). 127.0.0.1 would be the source address in this trace iirc.

**Comment by grs** [comment]
Ah, that explains it. 
I can't actually see the protocol header sent back from the router in the trace, unfortunately.

**Comment by grs** [comment]
I suspect in this case subserv may be connecting to itself. And because it has sasl enabled on the listener, but not on the connector, that is causing it to exit without sending back the protocol header.

At least that would be consistent with the packet capture...

**Comment by lulf** [comment]
Not seen this for a while, closing.
